// Generated by the gRPC protobuf plugin.
// If you make any local change, they will be lost.
// source: adn_exchange.proto
#ifndef GRPC_adn_5fexchange_2eproto__INCLUDED
#define GRPC_adn_5fexchange_2eproto__INCLUDED

#include "adn_exchange.pb.h"

#include <grpc++/impl/internal_stub.h>
#include <grpc++/impl/rpc_method.h>
#include <grpc++/impl/service_type.h>
#include <grpc++/async_unary_call.h>
#include <grpc++/status.h>
#include <grpc++/stream.h>

namespace grpc {
class CompletionQueue;
class ChannelInterface;
class RpcService;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace pathman {

class AdnExchange GRPC_FINAL {
 public:
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::pathman::Adn, ::pathman::Adn>> Shuffle(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::pathman::Adn, ::pathman::Adn>>(ShuffleRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::pathman::Adn, ::pathman::Adn>> AsyncShuffle(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::pathman::Adn, ::pathman::Adn>>(AsyncShuffleRaw(context, cq, tag));
    }
  private:
    virtual ::grpc::ClientReaderWriterInterface< ::pathman::Adn, ::pathman::Adn>* ShuffleRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::pathman::Adn, ::pathman::Adn>* AsyncShuffleRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
  };
  class Stub GRPC_FINAL : public StubInterface, public ::grpc::InternalStub {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    std::unique_ptr< ::grpc::ClientReaderWriter< ::pathman::Adn, ::pathman::Adn>> Shuffle(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::pathman::Adn, ::pathman::Adn>>(ShuffleRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::pathman::Adn, ::pathman::Adn>> AsyncShuffle(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::pathman::Adn, ::pathman::Adn>>(AsyncShuffleRaw(context, cq, tag));
    }

   private:
    ::grpc::ClientReaderWriter< ::pathman::Adn, ::pathman::Adn>* ShuffleRaw(::grpc::ClientContext* context) GRPC_OVERRIDE;
    ::grpc::ClientAsyncReaderWriter< ::pathman::Adn, ::pathman::Adn>* AsyncShuffleRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) GRPC_OVERRIDE;
    const ::grpc::RpcMethod rpcmethod_Shuffle_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);

  class Service : public ::grpc::SynchronousService {
   public:
    Service() : service_(nullptr) {}
    virtual ~Service();
    virtual ::grpc::Status Shuffle(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::pathman::Adn, ::pathman::Adn>* stream);
    ::grpc::RpcService* service() GRPC_OVERRIDE GRPC_FINAL;
   private:
    ::grpc::RpcService* service_;
  };
  class AsyncService GRPC_FINAL : public ::grpc::AsynchronousService {
   public:
    explicit AsyncService();
    ~AsyncService() {};
    void RequestShuffle(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::pathman::Adn, ::pathman::Adn>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag);
  };
};

}  // namespace pathman


#endif  // GRPC_adn_5fexchange_2eproto__INCLUDED
